; AWARE — ESP32-C5 Hauptprojekt
; WiFi Provisioning Captive Portal + ST7789 TFT + SD-Karte (shared SPI)

[env:esp32-c5-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32.git#develop
board = esp32-c5-devkitc1-n8r4
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
  -Wall
  -DPROV_DEBUG

lib_deps =
  adafruit/Adafruit GFX Library@^1.11.11
  adafruit/Adafruit ST7735 and ST7789 Library@^1.10.4
  greiman/SdFat@^2.2.3
